name: CPP UI Verify & Validation

# Need to update this for actual migration
trigger:
  branches:
    include:
      - main
      - 'team/*'
    exclude:
      - 'dev/release-*'
  paths:
    include:
      - '*'

pr:
  - '*'

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: 'hmcts'
      ref: 'main'

pool:
  name: 'MDV-ADO-AGENTS-01'

variables:
  sonarqubeProject: 'uk.gov.moj.cpp.ui:ui-results'

stages:
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - template: pipelines/ui-verify.yaml@cppAzureDevOpsTemplates
        parameters:
          sonarqube_project: ${{ variables['sonarqubeProject'] }}

  - ${{ if eq(variables['Build.Reason'], 'IndividualCI') }}:
      - template: pipelines/ui-validation.yaml@cppAzureDevOpsTemplates
        parameters:
          repo: '$(Build.Repository.Name)'
