<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>uk.gov.moj.cpp.ui</groupId>
        <artifactId>frontend-parent</artifactId>
        <version>1.6.2</version>
    </parent>

    <groupId>uk.gov.moj.cpp.ui</groupId>
    <artifactId>ui-results</artifactId>
    <version>19.0.4-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <protractor.baseUrl>http://localhost:4400</protractor.baseUrl>
        <protractor.apiUrl>${protractor.baseUrl}/api</protractor.apiUrl>
        <protractor.apiProxy>false</protractor.apiProxy>
        <protractor.uiProxy>false</protractor.uiProxy>
        <skip.node.install>false</skip.node.install>
        <skip.npm.install>false</skip.npm.install>
        <skip.npm.build>false</skip.npm.build>
        <skip.unit.tests>false</skip.unit.tests>
        <skip.dat.tests>true</skip.dat.tests>
        <skip.bat.tests>true</skip.bat.tests>
        <skip.report.pack>true</skip.report.pack>
        <skip.dist.pack>false</skip.dist.pack>
        <node.version>v18.20.4</node.version>
        <npm.version>10.7.0</npm.version>
        <cpp.environment />
        <npm.test.options />
        <npm.lint.options />
        <npm.build.options />
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>retrieve-cache</id>
                        <phase>process-sources</phase>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>${project.groupId}</groupId>
                                    <artifactId>${project.artifactId}</artifactId>
                                    <version>${project.version}</version>
                                    <classifier>cache</classifier>
                                    <type>tar.gz</type>
                                </artifactItem>
                            </artifactItems>
                            <outputDirectory>${project.basedir}</outputDirectory>
                            <skip>${skip.cache.retrieve}</skip>
                        </configuration>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <phase>initialize</phase>
                        <configuration>
                            <nodeVersion>${node.version}</nodeVersion>
                            <npmVersion>${npm.version}</npmVersion>
                            <nodeDownloadRoot>${node.download.root}</nodeDownloadRoot>
                            <npmDownloadRoot>${npm.download.root}</npmDownloadRoot>
                            <npmRegistryURL>${npm.registry.url}</npmRegistryURL>
                            <skip>${skip.node.install}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm config</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <arguments>config fix</arguments>
                            <skip>${skip.npm.install}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm ci</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <arguments>ci</arguments>
                            <skip>${skip.npm.install}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm version</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <arguments>version ${project.version} --force --allow-same-version
                                --no-git-tag-version</arguments>
                            <skip>${skip.npm.install}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm lint</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <arguments>run-script ci:lint -- ${npm.lint.options}</arguments>
                            <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
                            <skip>${skip.unit.tests}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm test</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <arguments>run-script ci:test -- ${npm.test.options}</arguments>
                            <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
                            <skip>${skip.unit.tests}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>prepare-package</phase>
                        <configuration>
                            <arguments>run-script ci:build -- ${npm.build.options}</arguments>
                            <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
                            <skip>${skip.npm.build}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm build:prod</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <arguments>run-script ci:build:prod -- ${npm.build.options}</arguments>
                            <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
                            <skip>${skip.npm.build}</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>dev</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>assembly/bin.xml</descriptor>
                            </descriptors>
                            <finalName>${project.artifactId}-${project.version}</finalName>
                            <appendAssemblyId>true</appendAssemblyId>
                            <archiverConfig>
                                <fileMode>0644</fileMode>
                                <directoryMode>0755</directoryMode>
                                <defaultDirectoryMode>0755</defaultDirectoryMode>
                            </archiverConfig>
                            <skipAssembly>${skip.dist.pack}</skipAssembly>
                        </configuration>
                    </execution>
                    <execution>
                        <id>bin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>assembly/bin.xml</descriptor>
                            </descriptors>
                            <finalName>${project.artifactId}-${project.version}</finalName>
                            <appendAssemblyId>false</appendAssemblyId>
                            <archiverConfig>
                                <fileMode>0644</fileMode>
                                <directoryMode>0755</directoryMode>
                                <defaultDirectoryMode>0755</defaultDirectoryMode>
                            </archiverConfig>
                            <skipAssembly>${skip.dist.pack}</skipAssembly>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>external.atlassian.jgitflow</groupId>
                <artifactId>jgitflow-maven-plugin</artifactId>
                <configuration>
                    <flowInitContext>
                        <masterBranchName>dev/release</masterBranchName>
                        <developBranchName>main</developBranchName>
                        <featureBranchPrefix>dev/feature-</featureBranchPrefix>
                        <releaseBranchPrefix>dev/release-</releaseBranchPrefix>
                        <hotfixBranchPrefix>dev/hotfix-</hotfixBranchPrefix>
                        <versionTagPrefix>v</versionTagPrefix>
                    </flowInitContext>
                    <pushReleases>${pushReleases}</pushReleases>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>3.11.0.3922</version>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>create-cache</id>
            <properties>
                <skip.cache.pack>false</skip.cache.pack>
            </properties>
        </profile>
        <profile>
            <id>use-cache</id>
            <properties>
                <skip.node.install>true</skip.node.install>
                <skip.npm.install>true</skip.npm.install>
                <skip.cache.pack>true</skip.cache.pack>
                <skip.cache.retrieve>false</skip.cache.retrieve>
            </properties>
        </profile>
        <profile>
            <id>skip-dist</id>
            <properties>
                <skip.dist.pack>true</skip.dist.pack>
            </properties>
        </profile>
        <profile>
            <id>skip-build</id>
            <properties>
                <skip.npm.build>true</skip.npm.build>
            </properties>
        </profile>
        <profile>
            <id>report</id>
            <properties>
                <skip.report.pack>false</skip.report.pack>
            </properties>
        </profile>
        <profile>
            <id>report-only</id>
            <properties>
                <skip.node.install>true</skip.node.install>
                <skip.npm.install>true</skip.npm.install>
                <skip.cache.pack>true</skip.cache.pack>
                <skip.cache.retrieve>true</skip.cache.retrieve>
                <skip.npm.build>true</skip.npm.build>
                <skip.unit.tests>true</skip.unit.tests>
                <skip.dat.tests>true</skip.dat.tests>
                <skip.dist.pack>true</skip.dist.pack>
                <skip.report.pack>false</skip.report.pack>
            </properties>
        </profile>
    </profiles>
</project>