sonar.projectKey=uk.gov.justice.cpp.ui:ui-results
sonar.projectName=@cpp:ui.results

sonar.projectDescription=CPP UI Hearing Results Application
sonar.links.homepage=https://github.com/hmcts/cpp-ui-results
#sonar.links.ci=
#sonar.links.issue=
sonar.links.scm=https://github.com/hmcts/cpp-ui-results
sonar.links.scm_dev=git@github.com:hmcts/cpp-ui-results.git

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=build/**/*,node_modules/**/*,dist/**/*,documentation/**

# Optional
#sonar.tests=test/**/*.js

# Tests
sonar.dependencyCheck.reportPath=build/dependency-check/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=build/dependency-check/dependency-check-report.html
#sonar.javascript.lcov.reportPaths=build/coverage/jest/lcov.info
sonar.typescript.exclusions=**/node_modules/**,**/bower_components/**,build/**,dist/**,documentation/**
sonar.typescript.lcov.reportPaths=build/coverage/jest/lcov.info
# SonarQube 7.2+ https://docs.sonarqube.org/display/PLUG/Importing+TSLint+issues+for+TypeScript+files
sonar.typescript.tslint.jsonReportPaths=build/lint/tslint.json
